{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"ens18\"}[5m])",
     "legendFormat": "Recive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"ens18\"}[5m])",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "CPU ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{instance=\"localhost:9100\",mode!=\"idle\"}[1m])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/sda1\",instance=\"localhost:9100\"} - node_filesystem_avail_bytes{device=\"/dev/sda1\",instance=\"localhost:9100\"}",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/sda1\",instance=\"localhost:9100\"}",
     "legendFormat": "{{device}}"
    },
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"localhost:9100\"} - node_memory_MemFree_bytes{instance=\"localhost:9100\"} - node_memory_Buffers_bytes{instance=\"localhost:9100\"} - node_memory_Cached_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "type": "welcome",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "type": "gettingstarted",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest from the blog",
   "type": "news",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {}
   ]
  }
 ]
}